version: "2"

services:
   db_node_domain:
     image: mysql:5.7
     volumes:
        - db_data:/var/lib/mysql
     restart: always
     environment:
        MYSQL_ROOT_PASSWORD: somewordpress
        MYSQL_DATABASE: wordpress2
        MYSQL_USER: wordpress2
        MYSQL_PASSWORD: wordpress2
     container_name: bestwedd_msql

   wordpress:
     depends_on:
        - db_node_domain
     image: wordpress:latest
     expose:
        - 80
     restart: always
     environment:
        VIRTUAL_HOST: bestweddingband.ie
        LETSENCRYPT_HOST: bestweddingband.ie
        LETSENCRYPT_EMAIL: foo@bestweddingband.ie
        WORDPRESS_DB_HOST: db_node_domain:3306
        WORDPRESS_DB_USER: wordpress
        WORDPRESS_DB_PASSWORD: wordpress
     container_name: bestwedd_web
volumes:
  db_data:

 networks:
   default:
     external:
       name: nginx-proxy
