version: "2"

services:
   ${node_domain}:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
       MYSQL_DATABASE: ${USERNAME}_wp
       MYSQL_USER: ${USERNAME}_adm
       MYSQL_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
     container_name: ${USERNAME}_db

   wordpress:
     depends_on:
       - ${node_domain}
     image: wordpress:latest
     expose:
       - 80
     restart: always
     environment:
       VIRTUAL_HOST: ${node_domain}
       WORDPRESS_DB_HOST: ${node_domain}:3306
       WORDPRESS_DB_USER: ${USERNAME}
       WORDPRESS_DB_PASSWORD: ${USER_PASSWORD}
     container_name: ${node_domain}
volumes:
    db_data:

networks:
  default:
    external:
      name: nginx-proxy
