version: "2"

services:
   db_node_domain:
     image: mysql:5.7
     volumes:
        - db_data:/var/lib/mysql
     restart: always
     environment:
        MYSQL_ROOT_PASSWORD: PtgCEBQmZan9Xgat
        MYSQL_DATABASE: ${username}_wp
        MYSQL_USER: ${username}_adm
        MYSQL_PASSWORD: PtgCEBQmZ
     container_name: ${username}_msql

   wordpress:
     depends_on:
        - db_node_domain
     image: wordpress:latest
     expose:
        - 80
        - 443
     restart: always
     environment:
        VIRTUAL_HOST: ${domain}
        LETSENCRYPT_HOST: ${domain}
        LETSENCRYPT_EMAIL: foo@${domain}
        WORDPRESS_DB_HOST: db_node_domain:3306
        WORDPRESS_DB_USER: thenetwpadmin
        WORDPRESS_DB_PASSWORD: PtgCEBQmZ
     container_name: ${username}_web
volumes:
  db_data:

networks:
   default:
     external:
       name: nginx-proxy
