version: '2'

services:
  example-app:
    image: wordpress/latest
    expose:
      - 80
    environment:
      VIRTUAL_HOST: buildersleads.com
      LETSENCRYPT_HOST: buildersleads.com
      LETSENCRYPT_EMAIL: foo@buildersleads.com

networks:
    default:
        external:
            name: nginx-proxy
